#!/usr/bin/env bash
# Configures Nginx with a custom HTTP header X-Served-By containing hostname
# This script is designed to configure a brand new Ubuntu machine

# Update package lists and install nginx if not already installed
apt-get -y update
apt-get -y install nginx

# Create a default index.html if it doesn't exist
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Get the hostname of the server
HOSTNAME=$(hostname)

# Make a backup of the default Nginx configuration
CONFIG_FILE="/etc/nginx/sites-available/default"
cp $CONFIG_FILE ${CONFIG_FILE}.backup

# Configure Nginx with the custom header
sed -i "/server_name _;/a \\\tadd_header X-Served-By $HOSTNAME;" $CONFIG_FILE

# Nginx configuration checks
nginx -t

# Restart Nginx service to apply changes
service nginx restart

exit 0
