#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 using round-robin algorithm

# Update packages
apt-get -y update
apt-get -y install haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup the original config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 STUDENT_ID-web-01:80 check
    server web-02 STUDENT_ID-web-02:80 check
EOF

# Start HAProxy service
service haproxy restart
