#!/usr/bin/env bash
# Reconfigure Nginx to listen on port 80 and start service
sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;\n\tlisten [::\]:80 default_server;/' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/ 2>/dev/null
rm /etc/nginx/sites-enabled/default 2>/dev/null
pkill nginx
service nginx start
