#!/usr/bin/env bash
sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;\n\tlisten [::\]:80 default_server;/' /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
service nginx start
