#!/usr/bin/env bash
# Script to configure Nginx with a custom HTTP header

# Update and install Nginx if not already installed
apt-get -y update
apt-get -y install nginx

# Create a custom index.html page
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx with custom header
# The header will include the hostname of the server
header_config="server_name _;\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/server_name _;/${header_config}/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
