#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server

# Update packages
apt-get -y update
apt-get -y install haproxy

# Enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup original config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create HAProxy configuration
cat > /etc/haproxy/haproxy.cfg << EOF
global
   log 127.0.0.1 local0 notice
   maxconn 2000
   user haproxy
   group haproxy

defaults
   log     global
   mode    http
   option  httplog
   option  dontlognull
   retries 3
   option redispatch
   timeout connect  5000
   timeout client  10000
   timeout server
