#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page

# Install nginx if not already installed
apt-get -y update
apt-get -y install nginx

# Create a custom 404 page with the required content
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
